## Attributes and Methods

In [3]:
import numpy as np

arr = np.arange(25)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape

In [8]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## max min argmax and argmin

In [11]:
ranarr=np.random.randint(0,50,10)
ranarr

array([21, 14,  6, 28,  2, 34, 41,  9, 30, 49])

In [13]:
ranarr.max()

49

In [15]:
ranarr.min()

2

In [17]:
ranarr.argmax()

9

In [19]:
ranarr.argmin()

4

## Shape

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.shape

(25,)

In [30]:
arr.reshape(1,25).shape

(1, 25)

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

## dtype

In [35]:
arr.dtype

dtype('int32')

## Numpy Indexing and Selection

In [38]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[5]

5

In [44]:
arr[1:5]

array([1, 2, 3, 4])

## Broadcasting

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
slice_of_arr = arr[0:5]
slice_of_arr

array([100, 100, 100, 100, 100])

In [53]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
slice_of_arr[:]=99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [59]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## Data is not copied , it's a view of original array only

In [62]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Copy and array into another array

In [64]:
arr_copy = arr.copy()

In [66]:
arr_copy[:]=99

In [68]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Indexing a 2D ARRAY

In [78]:
arr = np.arange(25)

In [80]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [82]:
arr = arr.reshape(5,5)

In [84]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
arr[0][0]

0

In [88]:
arr[2][3]

13

In [90]:
arr[2,3]

13