## Selection

In [2]:
import numpy as np
arr = np.arange(1,11)

In [4]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [8]:
bool_arr = arr>4

In [10]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [16]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [18]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
x = 3
arr[arr>x]

array([ 4,  5,  6,  7,  8,  9, 10])

## Numpy Operations

## Arithmentic Operations

In [31]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [37]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr/0

C:\Users\soumy\AppData\Local\Temp\ipykernel_1752\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [43]:
arr_zero = arr-arr

In [45]:
arr_zero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
arr_zero/arr_zero

C:\Users\soumy\AppData\Local\Temp\ipykernel_1752\316009236.py:1: RuntimeWarning: invalid value encountered in divide
  arr_zero/arr_zero


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [49]:
arr = np.arange(1,11)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

## Universal Array Functions

In [56]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [58]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [60]:
np.max(arr)

10

In [62]:
np.min(arr)

1

In [64]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [66]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])