# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

In [8]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays



In [2]:
my_list = [1,2,3]

In [4]:
my_list

[1, 2, 3]

In [12]:
arr = np.array(my_list)

In [14]:
type(arr)

numpy.ndarray

In [16]:
my_2d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [18]:
np.array(my_2d_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built In Methods

## arange

## Return evenly spaced values with a given interval

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## Zeros and Ones

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [32]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Linspace

Returns evenly spaced numbers over a specified interval

In [40]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [42]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Eye Matrix

Identity Matrix

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

In [51]:
## rand -- [0,1) - Uniform Distribution

np.random.rand(5)

array([0.01382616, 0.56293453, 0.19973802, 0.57835965, 0.73066287])

In [55]:
np.random.rand(5,5)

array([[0.75214441, 0.63773831, 0.6982254 , 0.88561609, 0.94538429],
       [0.36409912, 0.06886912, 0.15858256, 0.16594526, 0.45375428],
       [0.9920436 , 0.43024376, 0.12270596, 0.68050223, 0.40826594],
       [0.94512356, 0.18352022, 0.92943794, 0.52286103, 0.24158734],
       [0.51082725, 0.53745635, 0.62195489, 0.66043015, 0.11478664]])

In [57]:
##randint

In [59]:
np.random.randint(1,100)

24

In [61]:
np.random.randint(1,100,10)

array([53, 24, 90, 13, 46, 71, 50, 59, 46, 84])